application: what-slit
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: index.html
  upload: index\.html

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: whatslit.app

libraries:

- name: webapp2
  version: latest
- name: jinja2
  version: latest
